---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
myDF <- read.csv("activity.csv")
totalDF <- setNames(aggregate(myDF$steps ~ myDF$date, FUN = sum, na.rm = TRUE),c("date", "steps"))
```



## What is mean total number of steps taken per day?
```{r}
hist(totalDF$steps, main = "Total number of steps taken each day", xlab = "Total steps")
mean(totalDF$steps, na.rm = TRUE)
median(totalDF$steps, na.rm = TRUE)
```



## What is the average daily activity pattern?
```{r}
dailyAve <- setNames(aggregate(myDF$steps ~ myDF$interval, FUN = mean, na.rm = TRUE),c("interval", "steps"))
interval <- unique(myDF$interval)
plot(dailyAve$interval, dailyAve$steps, type = "l", xlab = "Interval", ylab = "Average steps")
dailyAve[which(dailyAve$steps == max(dailyAve$steps)),]
```



## Imputing missing values
My strategy is to replace the 'NA's with the mean of that 5-minute interval
```{r}
bad <- is.na(myDF$steps)
sum(bad)

aggregated <- aggregate(myDF$steps, by = list(myDF$interval), FUN = mean, na.rm = TRUE )
names(aggregated) <- c("interval", "stepsMean")

myDF <- merge(myDF, aggregated, by = "interval")
head(myDF)

myDF$imputedSteps <- rep(0, length(myDF$steps))
myDF$imputedSteps <- is.na(myDF$steps)*myDF$stepsMean
myDF$imputedSteps[!is.na(myDF$steps)] <- myDF$steps[!is.na(myDF$steps)]

imputedDF <- myDF[,c("interval", "imputedSteps", "date")]
names(imputedDF)[2] <- "steps"
totalDF.Imputed <- setNames(aggregate(imputedDF$steps ~ imputedDF$date, FUN = sum, na.rm = TRUE),c("date", "steps"))
hist(totalDF.Imputed$steps, main = "Total number of steps taken each day", xlab = "Total steps")
mean(totalDF.Imputed$steps, na.rm = TRUE)
median(totalDF.Imputed$steps, na.rm = TRUE)
```


## Are there differences in activity patterns between weekdays and weekends?
Turns out there are differences, see the plot below.
```{r}
library(lattice)
imputedDF$weekend <- weekdays(strptime(imputedDF$date, format = "%Y-%m-%d")) %in% c("Saturday","Sunday")
imputedDF$daytype[imputedDF$weekend] <- "weekend" 
imputedDF$daytype[!imputedDF$weekend] <- "weekday" 
imputedDF$daytype <- as.factor(imputedDF$daytype)
dailyAve.daytype <- setNames(aggregate(imputedDF$steps ~ imputedDF$interval + imputedDF$daytype, FUN = mean, na.rm = TRUE),c("interval","daytype", "steps"))
xyplot(steps ~ interval | daytype, data = dailyAve.daytype, layout = c(1,2), panel = function(x, y, ...) {
    panel.xyplot(x,y,type="l")
})
```
